version: '3.8'

services:
  passport-parsing:
    container_name: bd-passport-parsing
    image: passport-parsing:1.2
    restart: unless-stopped
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: all
             capabilities: [gpu]
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 5052:5052
